import React from 'react'

import About from '@/modules/about'

export const metadata = {
  title: 'About',
  description: 'Generated by create next app'
}

export default function AboutPage() {
  return <About />
}
